# Generated by Django 3.1.7 on 2021-03-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='alias2',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
