# Generated by Django 3.1.7 on 2021-03-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_hero_alias2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='alias2',
        ),
    ]
